import fs from 'fs';
import path from 'path';

export interface ProjectContext {
  projectName?: string;
  author?: string;
  history: Array<{
    type: string;
    timestamp: string;
    content: string;
  }>;
}

const PROJECT_DIR = '.gmpilot';
const CONTEXT_FILE = path.join(PROJECT_DIR, 'context.json');

export const projectManager = {
  isProject: (): boolean => {
    return fs.existsSync(PROJECT_DIR) && fs.lstatSync(PROJECT_DIR).isDirectory();
  },

  init: (name: string, author: string) => {
    // Legacy migration: if .gmpilot is a file, delete it
    if (fs.existsSync(PROJECT_DIR) && !fs.lstatSync(PROJECT_DIR).isDirectory()) {
      fs.unlinkSync(PROJECT_DIR);
    }

    if (!fs.existsSync(PROJECT_DIR)) {
      fs.mkdirSync(PROJECT_DIR);
    }
    const initialContext: ProjectContext = {
      projectName: name,
      author: author,
      history: []
    };
    fs.writeFileSync(CONTEXT_FILE, JSON.stringify(initialContext, null, 2));
  },

  get: (): ProjectContext => {
    if (!fs.existsSync(CONTEXT_FILE)) {
      return { history: [] };
    }
    try {
      const data = fs.readFileSync(CONTEXT_FILE, 'utf-8');
      return JSON.parse(data);
    } catch {
      return { history: [] };
    }
  },

  addEntry: (type: string, content: string) => {
    try {
      if (!projectManager.isProject()) return;
      const context = projectManager.get();
      context.history.push({
        type,
        timestamp: new Date().toISOString(),
        content
      });
      fs.writeFileSync(CONTEXT_FILE, JSON.stringify(context, null, 2));
    } catch (err) {
      // Silent fail
    }
  },

  getSummary: (): string => {
    try {
      if (!projectManager.isProject()) return "No project initialization found. Run 'gmpilot init' first.";
      const context = projectManager.get();
      if (context.history.length === 0) return "No previous history found for this project.";
      
      let summary = `Project: ${context.projectName} (Author: ${context.author})\n\nFull Project History:\n`;
      context.history.forEach((entry, i) => {
        summary += `--- Entry [${i+1}]: ${entry.type} (${new Date(entry.timestamp).toLocaleString()}) ---\n${entry.content}\n\n`;
      });
      return summary;
    } catch (err) {
      return "Error loading project history.";
    }
  },

  exportGDD: (): string | null => {
    try {
      if (!projectManager.isProject()) return null;
      const context = projectManager.get();
      const timestamp = new Date().toISOString().split('T')[0];
      const filename = `GDD_${context.projectName}_${timestamp}.md`;
      const filepath = path.join(process.cwd(), filename);

      let content = `# Game Design Document: ${context.projectName}\n`;
      content += `**Author:** ${context.author}\n`;
      content += `**Generated By:** GameMindPilot AI\n`;
      content += `**Date:** ${new Date().toLocaleString()}\n\n`;
      content += `--- \n\n`;
      content += `## 🏁 Executive Summary\n`;
      content += `This document contains the collected wisdom and designs for ${context.projectName}, generated through an AI-guided collaboration.\n\n`;

      context.history.forEach((entry) => {
        content += `## 📋 ${entry.type}\n`;
        content += `*Generated on ${new Date(entry.timestamp).toLocaleString()}*\n\n`;
        content += `${entry.content}\n\n`;
        content += `---\n\n`;
      });

      content += `\n*End of Document. Generated with GameMindPilot v3.0.0*\n`;

      fs.writeFileSync(filepath, content);
      return filepath;
    } catch (err) {
      return null;
    }
  },

  scanFiles(dir: string = process.cwd(), fileList: string[] = []): string[] {
    const ignored = ['node_modules', '.git', '.gmpilot', 'dist', 'package-lock.json', 'package.json', 'tsconfig.json'];
    try {
      const files = fs.readdirSync(dir);
      files.forEach(file => {
        const filePath = path.join(dir, file);
        const relPath = path.relative(process.cwd(), filePath);
        
        if (ignored.some(i => relPath.includes(i) || file === i)) return;

        if (fs.statSync(filePath).isDirectory()) {
          this.scanFiles(filePath, fileList);
        } else {
          fileList.push(relPath);
        }
      });
    } catch (e) {}
    return fileList;
  },

  applyChanges(changes: any[]) {
    const results: string[] = [];
    changes.forEach(change => {
      const fullPath = path.join(process.cwd(), change.path);
      const dir = path.dirname(fullPath);

      try {
        if (change.action === 'delete') {
          if (fs.existsSync(fullPath)) {
            fs.unlinkSync(fullPath);
            results.push(`Deleted: ${change.path}`);
          }
        } else {
          if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
          }
          fs.writeFileSync(fullPath, change.content);
          results.push(`${change.action === 'create' ? 'Created' : 'Updated'}: ${change.path}`);
        }
      } catch (err: any) {
        results.push(`Error on ${change.path}: ${err.message}`);
      }
    });
    return results;
  }
};
